server:
  port: 8070

#mybatis:
#  mapper-locations:
#  - sql_mappers/**/*.xml
  
spring:
  profiles:
    active: local
  datasource:
    hikari:
      jdbc-url: jdbc:mariadb://localhost:3306/ilovetennis
      driver-class-name: org.mariadb.jdbc.Driver
      username: root
      password: Rkawk1685$
      maximum-pool-size: 1500
      minimum-idle: 100
      connection-test-query: SELECT 1  
      max-lifetime: 200000   
#      
pagehelper:
  helper-dialect: mariadb
  reasonable: true
  support-methods-arguments: true      