server:
  port: 1685

spring:
  datasource:
    hikari:
      jdbc-url: jdbc:log4jdbc:postgresql://127.0.0.1:5432/postgres
      driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
      username: postgres
      password: 1234
    platform: postgres
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    open-in-view: false
    properties:
      hibernate:
        dialect: com.github.alexliesenfeld.querydsl.jpa.hibernate.PostgreSQLJsonDialect
        default_schema: public
    generate-ddl: true
    hibernate:
      ddl-auto: update
  data:
    rest:
      base-path: /api

springdoc:
  api-docs:
    path: /api-docs
    groups:
      enable: true
  swagger-ui:
    operations-sorter: alpha
    tags-sorter: alpha
    path: /swagger-ui.html
    disable-swagger-default-url: true
    display-query-params-without-oauth2: true