server:
  port: 3000
#jdbc:mysql://localhost:3306?useUnicode=true&characterEncoding=utf-8
spring:
  datasource:
      url: jdbc:mariadb://127.0.0.1:3306/ilovetennis?characterEncoding=utf-8
      driver-class-name: org.mariadb.jdbc.Driver
      username: root
      password: 1685
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDB103Dialect
        format_sql: true
        default_schema: public
        show-sql: false
    generate-ddl: true

  data:
    rest:
      base-path: /api

springdoc:
  api-docs:
    path: /api-docs
    groups:
      enable: true
  swagger-ui:
    operations-sorter: alpha
    tags-sorter: alpha
    path: /swagger-ui.html
    disable-swagger-default-url: true
    display-query-params-without-oauth2: true